# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:- master
run
execute 
pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    15
    Android 
     versionSpec: '20.x'
  displayName: 'Install Node.js'
Request Id: ee8292e3-a7ab-4128-b9dc-579976d68c01
Correlation Id: f39e0302-bd2e-4441-8f60-46ceca77eb74
Timestamp: 2024-11-15T22:56:41Z
Message: AADSTS50020 executes : User account 'juncarcastillon1988@gmail.com' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application '5926fc8e-304e-4f59-8bed-58ca97cc39a4'(Microsoft Intune portal extension) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
